comment: false
coverage:
  status:
    patch:
      default:
        target: 90%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
    project:
      default: off
      unit:
        target: 80%
        threshold: 0%
        flags: unit
      functional:
        target: 80%
        threshold: 0%
        flags: functional
