version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    labels:
      container_group: service
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      container_group: service
  db:
    image: postgres:9
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    labels:
      container_group: service
  invoices:
    build:
      context: ./services
      dockerfile: ./invoices/Dockerfile
    image: agavelab/ah-microservices-users
    links:
      - kafka
      - db
    environment:
      PORT: 80
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: invoices
    labels:
      container_group: service
