version: '2'

services:
  db:
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
  apigateway:
    volumes:
      - ./services/apigateway/src:/var/lib/app
      - ./services/apigateway/scripts:/home/docker
      - ./services/core:/var/lib/core
      # prevent mounting node_modules to avoid cross-platform incompatibilities
      - /var/lib/app/node_modules
    entrypoint: /home/docker/startup.integration.sh
  invoices:
    volumes:
      - ./services/invoices/src:/var/lib/app
      - ./services/invoices/scripts:/home/docker
      - ./services/core:/var/lib/core
      # prevent mounting node_modules to avoid cross-platform incompatibilities
      - /var/lib/app/node_modules
    entrypoint: /home/docker/startup.integration.sh
  users:
    entrypoint: /home/docker/startup.integration.sh
  grpc-gateway:
    entrypoint: /home/docker/startup.integration.sh
