version: '2'

services:
  apigateway:
    environment:
      NODE_ENV: test
    entrypoint: /home/docker/startup.test.sh
    volumes:
      - ./services/apigateway/unit_coverage:/var/lib/app/unit_coverage
      - ./services/apigateway/functional_coverage:/var/lib/app/functional_coverage
