KafkaBrokers:
  - "kafka:9092"
KafkaTopics:
  - "invoice"
ConsumerGroupID: "consumer-users"
DB:
  Host: "db"
  Port: 5432
  DBName: "users"
  Username: "postgres"
  Password: "postgres"
  Options:
    - "sslmode=disable"
Port: 80
