KafkaBrokers:
  - "localhost:9092"
KafkaTopics:
  - "invoice"
ConsumerGroupID: "consumer-users"
DB:
  DBHost: "localhost"
  DBPort: 5432
  DBName: "users"
  DBUser: "postgres"
  DBPassword: "postgres"
  DBOptions:
    - "sslmode=disable"
Port: 80
