version: '2'

services:
  users:
    entrypoint:
      - /home/docker/startup.test.sh
    volumes:
      - ./services/users/unit_coverage:/go/src/github.com/agave/ah-microservices/services/users/unit_coverage
#      - ./services/users/functional_coverage:/go/src/github.com/agave/ah-microservices/services/users/functional_coverage
